### ISSUE TITLE
Not working with latest cockpit

### ISSUE THREAD

**Issue by bfrye26** [enira/cockpit-smb-plugin#14]
Love the plugin, but it is not working with the latest cockpit version. I see you mention version 1.1 but I can't find the files for it. Are there any updates on this? Thanks for all the hard work, I love it!

**Comment by enira** [comment]
Thank you for the feedback.

Which version of cockpit are you running? As the latest version seems to be very different for each operating system. As for the version 1.1 question: there is an old user interface still present in the commits (but it's only compatible with old versions of cockpit). 


Can you provide me the samba, cockpit and OS version you are testing against?
For Centos based:
`yum info cockpit | grep -i "Version"`
For Debian based:
`apt-cache policy cockpit | grep -i "Installed"`
Also the same applies for the samba package.
And lastely some info about the OS.
`lsb_release -a`

I will retest the package against these versions.

**Comment by bfrye26** [comment]
Okay the Cockpit version is:
Version      : 215

Samba:
Version      : 4.11.7

As for OS:
Fedora Server 31 fresh insall

**Comment by bfrye26** [comment]
I could switch to CentOS 7 if that would be easier to setup in there. I am happy to try either if it would be less of a challange. Thanks for all your help with this

**Comment by enira** [comment]
I've had some testing yesterday, somewhere around version 210 a new user interface got introduced. So v 215 of cockpit is affected by this. Yesterday I got the user interface back working but with the new style, some rework needs to be done. Centos 7 should be pulling version 195.1-1, which still uses the old user interface. 215 compatible should be somewhere this week.

**Comment by bfrye26** [comment]
Well that is fantastic! The 215 version will be released on here once it is finished? If you need anyone for testing the code, I am happy to lend my computer for the purpose! Happy to help out these great open source projects!

**Comment by enira** [comment]
Yes, I will update the bug (set it to closed) once the fix is out. Will test against Fedora 31 and Ubuntu 19.10 backports.

**Comment by enira** [comment]
Tested against a fresh install if Fedora 31 and Project Cockpit 215, seems to be doing ok.
Install script also supports Fedora.
